# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload dependency graph

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
