name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    needs: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Override project version
        run: sed -i 's/version := ".*"/version := "${{ github.ref }}"/' build.sbt

      - name: Run sbt
        run: sbt compile

      - name: Package JAR
        run: sbt 'set packageOptions += Package.ManifestAttributes(
          "Implementation-Version" -> "${{ github.ref }}")' package

      - name: Rename JAR file
        run: mv target/scala-2.13/*.jar target/scala-2.13/app.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/scala-2.13/app.jar
          tag_name: ${{ github.ref }}