name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Set project version
        run: sed -i "s/version := \".*\"/version := \"${{ github.event.release.tag_name }}\"/" build.sbt

      - name: Run sbt
        run: sbt compile

      - name: Package JAR
        run: sbt package

      - name: Rename JAR file
        run: mv target/scala-2.13/*.jar target/scala-2.13/app.jar

      - name: Create universal zip
        run: sbt Universal/packageBin

      - name: Rename Universal zip file
        run: mv target/universal/*.zip target/universal/RM2_${{ github.ref:10 }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/scala-2.13/app.jar
            ./target/universal/RM2_${{ github.ref:10 }}.zip
          tag_name: ${{ github.ref:10 }}
